In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a = np.random.randn(100000)

In [3]:
df = pd.DataFrame(a)
df

0
0     -0.361568
1     -0.795287
2     -1.077969
3      0.842552
4      0.019430
...         ...
99995 -0.962978
99996 -1.410934
99997 -0.567523
99998  0.453639
99999 -0.514321

[100000 rows x 1 columns]

In [4]:
a = np.arange(50)

In [5]:
b = a.reshape(10,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
sliced = a[:4]
sliced[:] = 30

In [7]:
sliced ## changin the sliced array affects the original array

array([30, 30, 30, 30])

In [8]:
sliced2 = a[-4:].copy() ## when we use .copy(), then changing the sliced array does not affect the original array

In [9]:
sliced2[:] = 100

In [10]:
sliced2

array([100, 100, 100, 100])

In [11]:
a

array([30, 30, 30, 30,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
b

array([[30, 30, 30, 30,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [13]:
type(b)

numpy.ndarray

In [14]:
b[4,2]

22

In [15]:
b[:5, 2:]

array([[30, 30,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [16]:
x = [1,2,3]
y = [1,2,3]

In [17]:
np.cross(x,y)

array([0, 0, 0])

In [18]:
np.dot(x,y)

14

In [19]:
p = np.arange(5)
q = np.arange(4,9)

In [20]:
p,q

(array([0, 1, 2, 3, 4]), array([4, 5, 6, 7, 8]))

In [21]:
p + q ## addition of elements

array([ 4,  6,  8, 10, 12])

In [22]:
pq = np.concatenate((p,q))

In [23]:
p * q

array([ 0,  5, 12, 21, 32])

In [24]:
p/q

array([0.        , 0.2       , 0.33333333, 0.42857143, 0.5       ])

In [25]:
q/p

/tmp/ipykernel_10240/1828374478.py:1: RuntimeWarning: divide by zero encountered in divide
  q/p


array([       inf, 5.        , 3.        , 2.33333333, 2.        ])

In [26]:
## notice division by zero gives 'inf'

In [27]:
np.cos(np.pi)

-1.0

In [28]:
np.mean(x)

2.0

In [29]:
np.median(q/p)

/tmp/ipykernel_10240/256327094.py:1: RuntimeWarning: divide by zero encountered in divide
  np.median(q/p)


3.0

In [30]:
np.median([1,2,3,6])

2.5